import json
import re
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

from page_metadata_101 import PAGE_METADATA

raw_path = "scripts/ocr_raw_101.json"
out_path = r"c:\Users\user\Downloads\asdflkjh-main\edufox\frontend\public\articles\articles.json"

with open(raw_path, "r", encoding="utf-8-sig") as f:
    raw_pages = json.load(f)

# Comprehensive IELTS Academic Vocabulary dictionary with Uzbek translations & definitions
VOCAB_DICT = {
    "chromosome": ("xromosoma", "Irsiy axborotni saqlovchi hujayra yadrosi strukturasi", "noun", "/ˈkrəʊ.mə.səʊm/"),
    "cognitive": ("kognitiv, aqliy", "Idrok etish, bilish va aqliy faoliyatga oid", "adjective", "/ˈkɒɡ.nə.tɪv/"),
    "syndrome": ("sindrom, belgilar majmui", "Muayyan kasallikka xos bo'lgan belgilar yig'indisi", "noun", "/ˈsɪn.drəʊm/"),
    "inhibit": ("to'xtatmoq, sekinlashtirmoq", "Biror jarayon yoki ferment faolligini bosish yoki sekinlashtirish", "verb", "/ɪnˈhɪb.ɪt/"),
    "enzyme": ("ferment, biologik katalizator", "Tirik organizmdagi kimyoviy reaksiyalarni tezlashtiruvchi oqsil", "noun", "/ˈen.zaɪm/"),
    "supplement": ("qo'shimcha modda, vitamin", "Organizmga qo'shimcha oziq modda sifatida beriladigan vosita", "noun", "/ˈsʌp.lɪ.mənt/"),
    "genome": ("genom, genlar to'plami", "Organizmning irsiy ma'lumotlarining to'liq majmui", "noun", "/ˈdʒiː.nəʊm/"),
    "sequencing": ("sekvensiyalash, DNK ketma-ketligini aniqlash", "Genetik kod tartibini aniqlash jarayoni", "noun", "/ˈsiː.kwən.sɪŋ/"),
    "resilience": ("chidamlik, bardoshlilik", "Og'ir holatlardan keyin qayta tiklanish qobiliyati", "noun", "/rɪˈzɪl.i.əns/"),
    "degrade": ("yemirilmoq, parchalanmoq", "Vaqt o'tishi bilan kichikroq moddalarga ajralish", "verb", "/dɪˈɡreɪd/"),
    "contaminant": ("ifloslantiruvchi modda", "Atrof-muhit yoki mahsulot sofligini buzuvchi modda", "noun", "/kənˈtæm.ɪ.nənt/"),
    "microplastic": ("mikroplastik", "Hajmi 5 millimetrdan kichik bo'lgan plastik zarrachalar", "noun", "/ˌmaɪ.krəʊˈplæs.tɪk/"),
    "metabolic": ("metabolik, modda almashinuviga oid", "Organizmda moddalar va energiya almashinuvi bilan bog'liq", "adjective", "/ˌmet.əˈbɒl.ɪk/"),
    "therapeutic": ("terapevtik, shifobaxsh", "Davolovchi yoki sog'liqni yaxshilovchi xususiyatga ega", "adjective", "/ˌθer.əˈpjuː.tɪk/"),
    "pathology": ("patologiya, kasallik sabablari", "Kasalliklarning paydo bo'lishi va rivojlanishini o'rganish", "noun", "/pəˈθɒl.ə.dʒi/"),
    "neurological": ("nevrologik, asab tizimiga oid", "Miya va asab tizimi faoliyatiga taalluqli", "adjective", "/ˌnjʊə.rəˈlɒdʒ.ɪ.kəl/"),
    "transcription": ("transkripsiya, nusxa ko'chirish", "DNKdan RNKga genetik ma'lumot ko'chirilishi", "noun", "/trænˈskrɪp.ʃən/"),
    "immune": ("immunitetga ega, himoyalangan", "Kasallik yuqishidan biologik himoyalangan", "adjective", "/ɪˈmjuːn/"),
    "pathogen": ("patogen, kasallik qo'zg'atuvchi", "Organizmda kasallik keltirib chiqaruvchi mikroorganizm", "noun", "/ˈpæθ.ə.dʒən/"),
    "synthesis": ("sintez, birikma hosil qilish", "Oddiy moddalardan murakkabroq birikma yaratilishi", "noun", "/ˈsɪn.θə.sɪs/"),
    "sustainable": ("barqaror, tabiatga ziyon yetkazmaydigan", "Uzoq muddat davomida atrof-muhitni saqlab turuvchi", "adjective", "/səˈsteɪ.nə.bəl/"),
    "biodiversity": ("biologik xilma-xillik", "Muayyan hududdagi turfa xil organizmlar majmui", "noun", "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/"),
    "emission": ("chiqindi gazlar, ajralish", "Atmosferaga chiqariladigan ifloslovchi moddalar", "noun", "/iˈmɪʃ.ən/"),
    "hypothesis": ("gipoteza, ilmiy faraz", "Tajribada tekshirilishi lozim bo'lgan ilmiy taxmin", "noun", "/haɪˈpɒθ.ə.sɪs/"),
    "empirical": ("empirik, tajribaga asoslangan", "Nazariy emas, balki amaliy tajriba va kuzatish orqali olingan", "adjective", "/ɪmˈpɪr.ɪ.kəl/"),
    "significant": ("muhim, sezilarli", "Ahamiyatli va e'tiborga loyiq darajadagi", "adjective", "/sɪɡˈnɪf.ɪ.kənt/"),
    "correlation": ("o'zaro bog'liqlik, korrelyatsiya", "Ikki yoki undan ortiq hodisalar o'rtasidagi bog'lanish", "noun", "/ˌkɒr.əˈleɪ.ʃən/"),
    "predominant": ("yetakchi, asosiy, ustun", "Boshqalarga nisbatan kuchliroq yoki ko'proq bo'lgan", "adjective", "/prɪˈdɒm.ɪ.nənt/"),
    "phenomenon": ("fenomen, noyob hodisa", "Kuzatilishi mumkin bo'lgan g'ayritabiiy yoki ajoyib voqea", "noun", "/fəˈnɒm.ɪ.nən/"),
    "mechanism": ("mexanizm, ishlash tizimi", "Jarayonning qanday kechishini ta'minlovchi qismlar tizimi", "noun", "/ˈmek.ə.nɪ.zəm/"),
    "implication": ("oqibat, yashirin ma'no", "Biror harakat yoki kashfiyotdan kelib chiqadigan muhim natija", "noun", "/ˌɪm.plɪˈkeɪ.ʃən/"),
    "preliminary": ("dastlabki, kirish qismidagi", "Asosiy bosqichdan oldin o'tkaziladigan tayyorgarlik", "adjective", "/prɪˈlɪm.ɪ.nər.i/"),
    "infrastructure": ("infratuzilma", "Tizimning to'g'ri ishlashi uchun zarur tayanch tuzilmalar", "noun", "/ˈɪn.frəˌstrʌk.tʃər/"),
    "intervention": ("aralashuv, chora ko'rish", "Vaziyatni yaxshilash maqsadida amalga oshiriladigan chora", "noun", "/ˌɪn.təˈven.ʃən/"),
    "equilibrium": ("muvozanat, barqarorlik", "Turli kuchlar o'rtasida tenglik va barqarorlik holati", "noun", "/ˌek.wɪˈlɪb.ri.əm/"),
    "stimulation": ("rag'batlantirish, qo'zg'atish", "Faoliyat yoki o'sishni tezlashtirish jarayoni", "noun", "/ˌstɪm.jəˈleɪ.ʃən/"),
    "deteriorate": ("yemirilmoq, yomonlashmoq", "Sifat yoki holat jihatidan pasaymoq", "verb", "/dɪˈtɪə.ri.ə.reɪt/"),
    "receptive": ("qabul qiluvchan, moyil", "Yangi fikr yoki signallarni oson o'zlashtira oladigan", "adjective", "/rɪˈsep.tɪv/"),
    "fluctuate": ("tebranmoq, o'zgarib turmoq", "Bir me'yorda turmay yuqoriga va pastga siljimoq", "verb", "/ˈflʌk.tʃu.eɪt/"),
    "diminish": ("kamaymoq, susaymoq", "Hajmi yoki kuchi jihatidan kichraymoq", "verb", "/dɪˈmɪn.ɪʃ/"),
    "allocate": ("ajratmoq, taqsimlamoq", "Muayyan maqsad uchun resurs yoki mablag' ajratmoq", "verb", "/ˈæl.ə.keɪt/"),
    "inevitable": ("muqarrar, qochib bo'lmas", "Oldini olishning iloji bo'lmagan hodisa", "adjective", "/ɪnˈev.ɪ.tə.bəl/"),
    "substantial": ("sezilarli, salmoqli", "Hajmi yoki ahamiyati jihatidan katta bo'lgan", "adjective", "/səbˈstæn.ʃəl/"),
    "hominin": ("gominin, qadimgi odamsimon", "Zamonaviy odamlar va ularning yo'qolib ketgan qadimgi ajdodlari", "noun", "/ˈhɒm.ɪ.nɪn/"),
    "excavation": ("arxeologik qazishma", "Qadimiy qoldiqlarni topish uchun yerni qazish jarayoni", "noun", "/ˌeks.kəˈveɪ.ʃən/"),
    "artefact": ("qadimiy ashyo, artefakt", "Odamlar tomonidan yaratilgan tarixiy buyum", "noun", "/ˈɑː.tə.fækt/"),
    "fossil": ("qazilma boylik, tosh qotgan qoldiq", "Qadimiy tirik organizmning toshga aylangan qoldig'i", "noun", "/ˈfɒs.əl/"),
    "stratigraphy": ("stratigrafiya, qatlamlar ilmi", "Tog' jinslari va tuproq qatlamlarining ketma-ketligini o'rganish", "noun", "/strəˈtɪɡ.rə.fi/"),
    "divergence": ("farqlanish, ajralish", "Bitta ildizdan turli yo'nalishlarga bo'linib ketish", "noun", "/daɪˈvɜː.dʒəns/"),
    "bipedalism": ("ikki oyoqda yurish", "Ikkita oyoqda tik harakatlanish xususiyati", "noun", "/baɪˈpiː.dəl.ɪ.zəm/"),
    "symbiosis": ("simbioz, o'zaro manfaatli birgalik", "Turli organizmlarning bir-biriga foyda keltirib yashashi", "noun", "/ˌsɪm.baɪˈəʊ.sɪs/"),
    "mitochondria": ("mitoxondriya", "Hujayraning energiya ishlab chiqaruvchi asosiy organellasi", "noun", "/ˌmaɪ.təʊˈkɒn.dri.ə/"),
    "speciation": ("tur hosil bo'lishi", "Evolyutsiya jarayonida yangi biologik turning paydo bo'lishi", "noun", "/ˌspiː.ʃiˈeɪ.ʃən/"),
    "luminescence": ("lyuminessensiya, nurlanish", "Issiqliksiz sovuq yorug'lik chiqarish hodisasi", "noun", "/ˌluː.mɪˈnes.əns/"),
    "paleontology": ("paleontologiya", "O'tmishdagi o'simlik va hayvonot olamini o'rganuvchi fan", "noun", "/ˌpæl.i.ɒnˈtɒl.ə.dʒi/"),
    "anthropology": ("antropologiya", "Insonning kelib chiqishi va rivojlanishini o'rganuvchi fan", "noun", "/ˌæn.θrəˈpɒl.ə.dʒi/"),
    "sediment": ("cho'kindi jinslar", "Suv yoki shamol vositasida to'plangan zarrachalar qatlami", "noun", "/ˈsed.ɪ.mənt/"),
    "carcinogen": ("kanserogen, saraton qo'zg'atuvchi", "Tirik to'qimalarda saraton keltirib chiqaruvchi modda", "noun", "/kɑːˈsɪn.ə.dʒən/"),
    "epidemiology": ("epidemiologiya", "Kasalliklarning tarqalishi va sabablarini o'rganuvchi tibbiyot sohasi", "noun", "/ˌep.ɪ.diː.miˈɒl.ə.dʒi/"),
    "amnesia": ("amneziya, xotira yo'qolishi", "Miya shikastlanishi yoki kasallik sababli xotiraning yo'qolishi", "noun", "/æmˈniː.zi.ə/"),
    "consolidation": ("mustahkamlanish, barqarorlashuv", "Yangi xotiralarning mustahkam uzoq muddatli shaklga o'tishi", "noun", "/kənˌsɒl.ɪˈdeɪ.ʃən/"),
    "hippocampus": ("gippokamp, miya qismi", "Bosh miyada xotira va fazoviy mo'ljal olishga javobgar soha", "noun", "/ˌhɪp.əˈkæm.pəs/"),
    "neuroplasticity": ("neyroplastiklik", "Miyaning yangi tajribalar asosida o'zini qayta qurish qobiliyati", "noun", "/ˌnjʊə.rəʊ.plæsˈtɪs.ə.ti/"),
}

OCR_REPLACEMENTS = [
    (r'@MINDLESS.*', ''),
    (r'Your Go-To Source.*', ''),
    (r'Top-Tier Preparation.*', ''),
    (r'VK\.COM.*', ''),
    (r'VKCOM.*', ''),
    (r'WSNWS.*', ''),
    (r'PEfM3.*', ''),
    (r'PEnH3.*', ''),
    (r'Релиз подготовила.*', ''),
    (r'For (new|daily) stories.*', ''),
    (r'For more opinion.*', ''),
    (r'\bNewScientist\b.*', ''),
    (r'\bnewscientist\.com\b.*', ''),
    (r'NE-WS\s+(&\s+)?TECHNOLOGY', ''),
    (r'THIS\s+W(EE|FF)K', ''),
    (r'\bINSIGHT\b', ''),
    (r'\bANALYSIS\b', ''),
    (r'\bBRIEFING\b', ''),
    (r'\bCOVER\s+STORY\b', ''),
    (r'\bCOVFR\s+STORY\b', ''),
    (r'\bSPECIAL\s+REPORT\b', ''),
    (r'\bUNTOLD\s+STORY\b', ''),
    (r'\bIN\s+BRIEF\b', ''),
    (r'\bUPFRONT\b', ''),
    (r'\bCOMMENT\b', ''),
    (r'\bPROFILE\b', ''),
]

WORD_TYPO_FIXES = [
    (r'\bextra-t\b', 'extract'),
    (r'\bfeaturesof\b', 'features of'),
    (r'\bcomlK\)und\b', 'compound'),
    (r'\bepigalkxatechin-3-gal late\b', 'epigallocatechin-3-gallate'),
    (r'\bDYRKIA\b', 'DYRK1A'),
    (r'\bECrCG\b', 'EGCG'),
    (r'\bECGC\b', 'EGCG'),
    (r'\bEN\)isoned\b', 'poisoned'),
    (r'\bsigmx»sted\b', 'suggested'),
    (r'\bNudear\b', 'Nuclear'),
    (r'\bTh2\b', 'The'),
    (r'\bdcx•tcrs\b', 'doctors'),
    (r'\bq uickly\b', 'quickly'),
    (r'\bcriticallv\b', 'critically'),
    (r'\bclinician;\b', 'clinicians'),
    (r'\bIL uvel decade\b', 'It took over a decade'),
    (r'\bseq uence\b', 'sequence'),
    (r'\bprcxess\b', 'process'),
    (r'\bvirus-resigant\b', 'virus-resistant'),
    (r'\btcx\)l\b', 'tool'),
    (r'\brevoluuomsmg\b', 'revolutionising'),
    (r'\bpnetic\b', 'genetic'),
    (r'\bj ust\b', 'just'),
    (r'\bconnecticns\b', 'connections'),
    (r'\bexlrrienced\b', 'experienced'),
    (r'\bLos Angeks\b', 'Los Angeles'),
    (r'\btheres\b', "there's"),
    (r'\bpssica\b', 'Jessica'),
    (r'\btrom\b', 'from'),
    (r'\bblcui\b', 'blood'),
    (r'\bprotens\b', 'proteins'),
    (r'\battachb\b', 'attaches'),
    (r'\brodicol\b', 'radical'),
    (r'\bnpprnnrh tn\b', 'approach to'),
    (r'\bAbce Klein\b', 'Alice Klein'),
    (r'\bEk•ople\b', 'people'),
    (r'\bI-JK\b', 'UK'),
    (r'\bUR minds\b', 'Our minds'),
    (r'\btpcause\b', 'because'),
    (r'\bmemori2s\b', 'memories'),
    (r'\bshcrs\b', 'shoes'),
    (r'\bzgainst\b', 'against'),
    (r'\bMhat\b', 'what'),
    (r'\bEKK:iy\b', 'body'),
    (r'\bte»l\b', 'tool'),
    (r'\bhipgxxarnpus\b', 'hippocampus'),
    (r'\bapvral\b', 'appeal'),
    (r'\byotr\b', 'your'),
    (r'\bcmstantly\b', 'constantly'),
    (r'\bbJt\b', 'but'),
    (r'\bhep\b', 'help'),
    (r'\btpst\b', 'best'),
    (r'\balternativ21y\b', 'alternatively'),
    (r'\bcnrrnhnrate\b', 'corroborate'),
    (r'\bperenn\b', 'person'),
    (r'\bRut right now\b', 'But right now'),
    (r'\bTcx»\b', 'Too'),
    (r'\bpecple\b', 'people'),
    (r'\bpcx\.rer\b', 'poorer'),
    (r'\bsatellie\b', 'satellite'),
    (r'\brrwnory\b', 'memory'),
    (r'\bedJcation\b', 'education'),
    (r'\bdisappoirtment\b', 'disappointment'),
    (r'\bbumt Ik\)nes\b', 'burnt bones'),
    (r'\bourancestors\b', 'our ancestors'),
    (r'\bhistoryhas\b', 'history has'),
    (r'\bSS8-mi Ilion\b', '558-million'),
    (r'\bcreaturewas\b', 'creature was'),
    (r'\bgtarded\b', 'guarded'),
    (r'\bYanllkaya\b', 'Yazılıkaya'),
    (r'\bMichæl\b', 'Michael'),
    (r'\bPuppy-Jay\b', 'New Scientist'),
]

MASTER_REPLACEMENTS = [
    # Strip parenthetical citation leaks like (doi.org/...), (bioRxiv, doi.org/...), (Nature, doi.org/...)
    (r'\((?:bioRxiv|Nature|Science|arxiv|doi|doinrg|doiorg|Cell|Genome|Lancet|PNAS)[^)]*\)', ''),
    (r'\b(?:doi\.org|arxiv\.org|doinrg|doiorg)/[a-zA-Z0-9_\-\./]+\b', ''),
    (r'\b10\.\d{4,9}/[-._;()/:A-Za-z0-9]+\b', ''),

    # AI and Numbers
    (r'\bA1\b', 'AI'),
    (r"\bA1's\b", "AI's"),
    (r'\b201B\b', '2018'),
    (r'\b10T\b', 'IoT'),
    (r'\btas9\b', 'Cas9'),
    (r'\bw0\b', 'two'),
    (r'\bth2Y\b', 'they'),
    (r'\bth2y\b', 'they'),
    (r'\bthe1957\b', 'the 1957'),
    (r'\btheir70s\b', 'their 70s'),
    (r'\b270ctober\b', '27 October'),
    (r'\b27CRtober\b', '27 October'),
    (r'\b26January\b', '26 January'),
    (r'\b22June20191\b', '22 June 2019'),
    (r'\bMarth2018\b', 'March 2018'),
    (r'\banc2014\b', 'and 2014'),
    (r'\b4.1-billionyear-old\b', '4.1-billion-year-old'),
    (r'\b600-millbnyear-old\b', '600-million-year-old'),
    (r'\b3-95-billion-year-old\b', '3.95-billion-year-old'),
    (r'\b7cx\',000\b', '700,000'),
    (r'\b43,0cx\b', '43,000'),
    (r'\b80cx\b', '800'),
    # Specific OCR token repairs
    (r'\bNew-?saentist\w*\b', ''),
    (r'\bz0181Newscjentist\w*\b', ''),
    (r'\bNewScientist\d+\w*\b', ''),
    (r'\bNewsoentist\w*\b', ''),
    (r'\bNew9ientist\w*\b', ''),
    (r'\bcrÉrü1ds\b', 'cards'),
    (r"\b8'0ther\b", 'other'),
    (r'\bavailaD1e\b', 'available'),
    (r'\b14New\b', '14 New'),
    (r'\bsup1K\)rting\b', 'supporting'),
    (r'\bintelliW1ce\b', 'intelligence'),
    (r'\bnx-2016\b', '2006-2016'),
    (r'\bÜ\)5-2015\b', '2005-2015'),
    (r'\'"2CD4-2014', '2004-2014'),
    (r'\b1k\)int\b', 'point'),
    (r'\b1K\)int\b', 'point'),
    (r'\bmpmnripq7\b', 'memories'),
    (r'\bex1X\)sing\b', 'exposing'),
    (r'\bscmrurT1\b', 'screen'),
    (r'\bt21ng\b', 'taking'),
    (r'\b2nergy\b', 'energy'),
    (r'\breaW1\b', 'reach'),
    (r'\bcorTV1ents\b', 'components'),
    (r'\bhagF1ed\b', 'hailed'),
    (r'\bwtW1\b', 'when'),
    (r'\b7to\b', '7 to'),
    (r'\btcxx1\b', 'food'),
    (r'\bSl\.9\b', '51.9'),
    (r"\bA17hpimor'?", "Alzheimer's"),
    (r'\bSz89\b', '89'),
    (r'\bS78\b', '78'),
    (r'\batXX1t\b', 'about'),
    (r'\bgam2-like\b', 'game-like'),
    (r'\bcomlxR1nd\b', 'compound'),
    (r'\bageing"\.9,\b', 'ageing."'),
    (r'\bofArchae01cyical\b', 'of Archaeological'),
    (r'\b709\.cx\b', '700,000'),
    (r'\bt17\.nn\b', 'then'),
    (r'\bpr0B\)sed\b', 'proposed'),
    (r'\blandsca1X\b', 'landscape'),
    (r'\bhydrow1\b', 'hydrogen'),
    (r'\b170,ocx\)\b', '170,000'),
    (r'\b3\.g\b', '3.9'),
    (r'\baEm1t\b', 'admit'),
    (r'\b3f\b', 'of'),
    (r'\bJOä0\b', '50'),
    (r'\b60,ooo\b', '60,000'),
    (r'\b20t\b', '20'),
    (r'\bChac6n\b', 'Chacón'),
    (r'\bnf19\b', 'of 19'),
    (r"\bim1X'ssible\b", 'impossible'),
    (r'"1Ky', '1 kg'),
    (r'\bR060\b', 'settlement'),
    (r'\b2-kilometredeep\b', '2-kilometre-deep'),
    (r'\bbluklist2d\b', 'blocklisted'),
    (r'\babs/[a-z0-9\.]+\)?', ''),
    (r'\bcn9g\)\.', ''),
    (r'\bdoi\.0rg/ckn9\)\.', ''),
    (r'\b101\.qaY2018\b', ''),
    (r'\b\d+\.qaY\d+\b', ''),
    (r'35\([xX]\)', '3,500'),
    (r'709\.cx', '700,000'),
    (r'\bt17\.nn\b', 'then'),
    (r'170,ocx\)', '170,000'),
    (r'60,ooo', '60,000'),
    (r'Chac6n', 'Chacón'),
    (r'ageing"\.9,', 'ageing."'),
    (r'\b180C\b', '18°C'),
    (r'\b210C\b', '21°C'),
    (r"\b20'C\b", '20°C'),
    (r"\b4700'C\b", '4700°C'),
    (r'\b40\.8m\b', '40.8 m'),
    (r'\bM15\b', '15'),

    # Common OCR 'cx' -> 'o' / 'oo'
    (r'\b(b|m|r)cxiel\b', r'\1odel'),
    (r'\b(m|r)cxierate\b', r'\1oderate'),
    (r'\b(m|r)cxiern\b', r'\1odern'),
    (r'\b(m|r)cxlern\b', r'\1odern'),
    (r'\b(m|r)cxiified\b', r'\1odified'),
    (r'\bmcxidulate\b', 'modulate'),
    (r'\bmcxdiulate\b', 'modulate'),
    (r'\bmcxulate\b', 'modulate'),
    (r'\bmetalm•lism\b', 'metabolism'),
    (r'\bmethcxi\b', 'method'),
    (r'\bmethcxis\b', 'methods'),
    (r'\bmethcxls\b', 'methods'),
    (r'\bmitck•hondria\b', 'mitochondria'),
    (r'\bmitcxhondria\b', 'mitochondria'),
    (r'\bmitcxhondrion\b', 'mitochondrion'),
    (r'\bneighbourhcxxls\b', 'neighbourhoods'),
    (r'\bmotherhcx»d\b', 'motherhood'),
    (r'\boffshcx\)ts\b', 'offshoots'),
    (r'\bolx•sity\b', 'obesity'),
    (r'\boverccx\)ked\b', 'overcooked'),
    (r'\bprcxessing\b', 'processing'),
    (r'\bprcxession\b', 'procession'),
    (r'\bprcxessions\b', 'processions'),
    (r'\bprcxiuce\b', 'produce'),
    (r'\bprcxiucing\b', 'producing'),
    (r'\bprcxluced\b', 'produced'),
    (r'\bprcxlucing\b', 'producing'),
    (r'\bprcxiuct\b', 'product'),
    (r'\bprcxiucts\b', 'products'),
    (r'\bprcxluct\b', 'product'),
    (r'\bprcxluctivity\b', 'productivity'),
    (r'\bprovcxative\b', 'provocative'),
    (r'\brcx\)ms\b', 'rooms'),
    (r'\brcx\)rn\b', 'room'),
    (r'\brcx\)ted\b', 'rooted'),
    (r'\brcx\)ts\b', 'roots'),
    (r'\brcxk\b', 'rock'),
    (r'\brcxks\b', 'rocks'),
    (r'\brcxket\b', 'rocket'),
    (r'\bresvx•nse\b', 'response'),
    (r'\brx»tential\b', 'potential'),
    (r'\brx•ssible\b', 'possible'),
    (r'\bvx»ssible\b', 'possible'),
    (r'\bschcx\)lchildren\b', 'schoolchildren'),
    (r'\bschcx»l\b', 'school'),
    (r'\bschcx\)l\b', 'school'),
    (r'\bscx\)n\b', 'soon'),
    (r'\bscx»ner\b', 'sooner'),
    (r'\bscxial\b', 'social'),
    (r'\bscxially\b', 'socially'),
    (r'\bscxieties\b', 'societies'),
    (r'\bscxiety\b', 'society'),
    (r'\bs«ieties\b', 'societies'),
    (r'\bscx»thing\b', 'soothing'),
    (r'\btadgx»les\b', 'tadpoles'),
    (r'\btcx\)ls\b', 'tools'),
    (r'\btcx•ls\b', 'tools'),
    (r'\btcxiay\b', 'today'),
    (r'\btcxlay\b', 'today'),
    (r'\btcxjk\b', 'took'),
    (r'\btcx»\b', 'too'),
    (r'\btx»rnbarded\b', 'bombarded'),
    (r'\btx»mbardment\b', 'bombardment'),
    (r'\btx»ost\b', 'boost'),
    (r'\bunlcxked\b', 'unlocked'),
    (r'\bwcxxlen\b', 'wooden'),
    (r'\bwcx»den\b', 'wooden'),
    (r'\bwc»den\b', 'wooden'),
    (r'\bwcxxlland\b', 'woodland'),
    (r'\bzcx»keepers\b', 'zookeepers'),
    (r'\bcarlx»n\b', 'carbon'),
    (r'\bcartx»n-dated\b', 'carbon-dated'),
    (r'\bccxaine\b', 'cocaine'),
    (r'\bccxktails\b', 'cocktails'),
    (r'\bccx»ler\b', 'cooler'),
    (r'\bccx•aine\b', 'cocaine'),
    (r'\bccx•peration\b', 'cooperation'),
    (r'\bchildhcx\.xl\b', 'childhood'),
    (r'\bchildhcxxi\b', 'childhood'),
    (r'\bdcxtor\b', 'doctor'),
    (r'\bdcxtors\b', 'doctors'),
    (r'\bdcxument\b', 'document'),
    (r'\bdcxumenting\b', 'documenting'),
    (r'\bfcx\)d\b', 'food'),
    (r'\bfcxus\b', 'focus'),
    (r'\bfcxxi\b', 'food'),
    (r'\bfcxxl\b', 'food'),
    (r'\bfcxxls\b', 'foods'),
    (r'\bfcx•t\b', 'foot'),
    (r'\bfcx»t\b', 'foot'),
    (r'\bFcx\)t\b', 'Foot'),
    (r'\bFcx»t\b', 'Foot'),
    (r'\bflcxxiplains\b', 'floodplains'),
    (r'\bgcx\b', 'good'),
    (r'\bgcx-\'d\b', 'good'),
    (r'\bgcx»d\b', 'good'),
    (r'\bgc»d\b', 'good'),
    (r'\bhcxkey\b', 'hockey'),
    (r'\bhcxwering\b', 'hovering'),
    (r'\bintrcxluction\b', 'introduction'),
    (r'\bkncxk\b', 'knock'),
    (r'\blcx\)king\b', 'looking'),
    (r'\blcxated\b', 'located'),
    (r'\blcxked\b', 'looked'),
    (r'\blcx»ked\b', 'looked'),
    (r'\blcx»king\b', 'looking'),
    (r'\blc»k\b', 'look'),
    (r'\btcx\)th\b', 'tooth'),
    (r'\btx»th\b', 'both'),
    (r'\batx»ut\b', 'about'),
    (r'\batx•ut\b', 'about'),
    (r'\balx»ut\b', 'about'),
    (r'\balx•ut\b', 'about'),
    (r'\baln»ut\b', 'about'),
    (r'\btx•fore\b', 'before'),
    (r'\btk•fore\b', 'before'),
    (r'\btk•cause\b', 'because'),
    (r'\btm•ause\b', 'because'),
    (r'\bb«ause\b', 'because'),
    (r'\bc_lildren\b', 'children'),
    (r'\bChildr2n\b', 'Children'),
    (r'\b0th2rwise\b', 'otherwise'),
    (r'\bdecad2s\b', 'decades'),
    (r'\btrain2d\b', 'trained'),
    (r'\bearli2st\b', 'earliest'),
    (r'\bn2ver\b', 'never'),
    (r'\bA17hpimor\'<—\b', "Alzheimer's"),
    (r'\bAlzheimer\*s\b', "Alzheimer's"),
    (r'\bAn«tralia\b', 'Australia'),
    (r'\bBcxiy\b', 'Body'),
    (r'\bBcxldington\b', 'Boddington'),
    (r'\bBl«\'d\b', 'Blood'),
    (r'\bCc\*e\b', 'Cave'),
    (r'\bDcxtors\b', 'Doctors'),
    (r'\bRutg«s\b', 'Rutgers'),
    (r'\bAB\)E4\b', 'APOE4'),
    (r'\bI>nisovans\b', 'Denisovans'),
    (r'\bPäätx»\b', 'Pääbo'),
    (r'\bSmilcxion\b', 'Smilodon'),
    (r'\bSmilcxton\b', 'Smilodon'),
    (r'\bLiveqx•ol\b', 'Liverpool'),
    (r'\bMellx»urne\b', 'Melbourne'),
    (r'\bMild-to-mcxlerate\b', 'Mild-to-moderate'),
    (r'\bpe•ople\b', 'people'),
    (r'\bp«ple\b', 'people'),
    (r'\brk•ople\b', 'people'),
    (r'\brx•ople\b', 'people'),
    (r'\bvx•oplc\b', 'people'),
    (r'\bE\.k•ople\b', 'people'),
    (r'\bIk\.\*ople\b', 'people'),
    (r'\b\*ople\b', 'people'),
    (r'\bEk•cies\b', 'species'),
    (r'\bsly•cies\b', 'species'),
    (r'\bspecie•s\b', 'species'),
    (r'\bEk•nding\b', 'spending'),
    (r'\bEk•rceptions\b', 'perceptions'),
    (r'\bEk•rhaps\b', 'perhaps'),
    (r'\bFk•rhaps\b', 'perhaps'),
    (r'\bGlotx•lly\b', 'Globally'),
    (r'\bIk•come\b', 'become'),
    (r'\bIk•en\b', 'been'),
    (r'\bIk•gan\b', 'began'),
    (r'\bIk•haviour\b', 'behaviour'),
    (r'\bIk•low\b', 'below'),
    (r'\bkk•haviours\b', 'behaviours'),
    (r'\bknw•ledge\b', 'knowledge'),
    (r'\bineffe•ctiw\b', 'ineffective'),
    (r'\binfe•ctions\b', 'infections'),
    (r'\bde•æloping\b', 'developing'),
    (r'\bdire•ctor\b', 'director'),
    (r'\bevarx•ration\b', 'evaporation'),
    (r'\bhaplk•ned\b', 'happened'),
    (r'\bvolunte•ers\b', 'volunteers'),
    (r'\bti•at\b', 'that'),
    (r'\btha•\b', 'that'),
    (r'\bsupl_xysedly\b', 'supposedly'),
    (r'\bshcxk\b', 'shock'),
    (r'\bremer_ber\b', 'remember'),
    (r'\bremernty•r\b', 'remember'),
    (r'\bpre•dators\b', 'predators'),
    (r'\bpignu•nt\b', 'pigment'),
    (r'\bmillimotr••«\b', 'millimetres'),
    (r'\bmakø«\b', 'makes'),
    (r'\bmanag«s\b', 'manages'),
    (r'\bsay«\b', 'says'),
    (r'\bstudi«i\b', 'studied'),
    (r'\bus«l\b', 'used'),
    (r'\byear«\b', 'years'),
    (r'\bdeath«\b', 'deaths'),
    (r'\bobj«t\b', 'object'),
    (r'\bsmack•d\b', 'smacked'),
    (r'\bsnort4ived\b', 'short-lived'),
    (r'\btriw•ring\b', 'triggering'),
    (r'\byearsag•\b', 'years ago'),
    (r'\bNew\*ientist\b', 'New Scientist'),
    (r'\bWhat•s\b', "What's"),
    (r'\bParmentier•s\b', "Parmentier's"),
    (r'\bDeSanti«\b', 'DeSantis'),
    (r'\bPict«\b', 'Picts'),

    # Exhaustive in-paragraph OCR word & punctuation repairs
    ('\\((?:bioRxiv|Nature|Science|arxiv|doi|doinrg|doiorg|Cell|Genome|Lancet|PNAS)[^)]*\\)', ''),
    ('\\b(?:doi\\.org|arxiv\\.org|doinrg|doiorg)/[a-zA-Z0-9_\\-\\./]+\\b', ''),
    ('\\b(?:aryiv\\.org|arxiv\\.orwaDs)/[a-zA-Z0-9_\\-\\./]*\\b', ''),
    ('\\b10\\.\\d{4,9}/[-._;()/:A-Za-z0-9]+\\b', ''),
    ('\\(arxiv\\.\\s*', '('),
    ('\\b101\\.qaY2018\\b', ''),
    ('\\b\\d+\\.qaY\\d+\\b', ''),
    ('\\bofJohns\\s+Hopkins\\b', 'of Johns Hopkins'),
    ('\\bZealandJournal\\b', 'Zealand Journal'),
    ('\\bofPsychiatry\\b', 'of Psychiatry'),
    ('\\bAliceKlein\\b', 'Alice Klein'),
    ('\\bHanna-AttishaS\\b', "Hanna-Attisha's"),
    ('\\bXiaS\\b', "Xia's"),
    ('\\bAlmso-SerramS\\b', "Alonso-Serrano's"),
    ('\\bsaysZilhäo\\b', 'says Zilhão'),
    ('\\bvictimofVictorian\\b', 'victim of Victorian'),
    ('\\bofSt\\s+Andrews\\b', 'of St Andrews'),
    ('\\bofPhysical\\s+Anthropology\\b', 'of Physical Anthropology'),
    ('\\bofOslo\\b', 'of Oslo'),
    ('\\bGrimS\\b', "Grim's"),
    ('\\bofTor\\s+Faraj\\b', 'of Tor Faraj'),
    ('\\bdepthsofBruniquelcavein\\b', 'depths of Bruniquel cave in'),
    ('\\bKaytSukel\\b', 'Kayt Sukel'),
    ('\\bNewSCientistI?\\b', 'New Scientist'),
    ('\\bNevV\\s+YlentiSt\\b', 'New Scientist'),
    ('\\bParmentier•s\\b', "Parmentier's"),
    ('\\bWhat•s\\b', "What's"),
    ('\\b118TH-CENTURY\\b', '18TH-CENTURY'),
    ('\\b130/0\\b', '13%'),
    ('\\b709\\.cx\\b', '700,000'),
    ('\\b170,ocx\\)?\\b', '170,000'),
    ('\\b60,ooo\\b', '60,000'),
    ('\\bICX\\)O\\b', '1000'),
    ('ageing"\\.9,?', 'ageing."'),
    ('\\büt-inWi-Fi\\b', 'built-in Wi-Fi'),
    ("\\bM\\'/hnrhininfected\\b", 'Wolbachia-infected'),
    ("\\b\\'thidhcxxi\\b", 'childhood'),
    ('\\beverybcxfys\\b', "everybody's"),
    ('\\bforefcx\\)t\\b', 'forefoot'),
    ('\\bofboxwcxxl\\b', 'of boxwood'),
    ('\\boftcx\\)l\\b', 'of tool'),
    ('\\bpericx:lic\\b', 'periodic'),
    ('\\bpericxi\\b', 'period'),
    ('\\bprcxiuction\\b', 'production'),
    ('\\brncx\\)rland\\b', 'moorland'),
    ('\\brncxiel\\b', 'model'),
    ('\\brncxiern\\b', 'modern'),
    ('\\brncxiified\\b', 'modified'),
    ('\\brncxlerate\\b', 'moderate'),
    ('\\brncxlern\\b', 'modern'),
    ('\\btetrahydrcxannabinol\\b', 'tetrahydrocannabinol'),
    ('\\bRcxlrigo\\b', 'Rodrigo'),
    ('\\bScx\\s+n\\b', 'Soon'),
    ('\\bScx\\b', 'Soon'),
    ('\\bTcx\\b', 'Too'),
    ('\\btcx\\b', 'too'),
    ('\\btcxy\\b', 'too'),
    ('\\btcx\\)th\\b', 'tooth'),
    ('\\btcx\\)ls\\b', 'tools'),
    ('\\btcx•ls\\b', 'tools'),
    ('\\btcx\\)k\\b', 'took'),
    ('\\btcxjk\\b', 'took'),
    ('\\btcx»\\b', 'too'),
    ('\\btcxiay\\b', 'today'),
    ('\\btcxlay\\b', 'today'),
    ('\\btX\\)th\\b', 'both'),
    ('\\btX\\)x\\b', 'box'),
    ('\\btX\\)nes\\b', 'bones'),
    ('\\btX\\)ne\\b', 'bone'),
    ('\\btX\\)rn\\b', 'born'),
    ('\\btX\\)ut\\b', 'about'),
    ('\\bF-tX\\)t\\b', 'Little Foot'),
    ("\\bFcX\\'t\\b", 'Little Foot'),
    ("\\bttN\\'ls\\b", 'tools'),
    ('\\bctX\\)king\\b', 'cooking'),
    ('\\bchtH\\)se\\b', 'choose'),
    ('\\bbcxiies\\b', 'bodies'),
    ('\\bbcxi\\b', 'body'),
    ('\\bgocxi\\b', 'good'),
    ('\\bgcR\\)d\\b', 'good'),
    ('\\bblcxxl\\b', 'blood'),
    ('\\bblcxxi\\b', 'blood'),
    ('\\bblocxi\\b', 'blood'),
    ('\\bblocYl\\b', 'blood'),
    ('\\bblcx\\s+d\\b', 'blood'),
    ('\\bblcx\\b', 'blood'),
    ('\\bblcxk\\b', 'block'),
    ('\\bblcxky\\b', 'blocky'),
    ('\\bbluklist2d\\b', 'blocklisted'),
    ('\\bbcx\\)sting\\b', 'boosting'),
    ("\\bpcx\\'r\\b", 'poor'),
    ('\\bpcxkets\\b', 'pockets'),
    ('\\bfocxl\\b', 'food'),
    ('\\bharlX\\)ur\\b', 'harbour'),
    ('\\bdelH\\)sits\\b', 'deposits'),
    ('\\bdeB\\)sited\\b', 'deposited'),
    ('\\bproENNtion\\b', 'proportion'),
    ('\\bresERctively\\b', 'respectively'),
    ('\\bStrilR\\b', 'Strike'),
    ('\\bplacTtx\\)s\\b', 'placebos'),
    ('\\bsEk\\)rty\\b', 'sporty'),
    ('\\bncxem\\b', 'nocebo'),
    ('\\bexErctations\\b', 'expectations'),
    ('\\bproslRct\\b', 'prospect'),
    ('\\bwell-tRing\\b', 'well-being'),
    ('\\bernFX\\)wered\\b', 'empowered'),
    ('\\boWious\\b', 'obvious'),
    ('\\bfM\\b', 'for'),
    ('\\bttBt\\b', 'that'),
    ('\\bcnrtOV\\b', 'cortex'),
    ('\\btylR\\s+s\\b', 'types of'),
    ('\\btylR\\b', 'types'),
    ('\\bbrainSprcxess\\b', "brain's process"),
    ('\\bremerT&r\\b', 'remember'),
    ('\\bInivprqit/\\b', 'University'),
    ('\\bNewHampshire\\b', 'New Hampshire'),
    ('\\bmatpriAl\\b', 'material'),
    ('\\bmcEt\\b', 'most'),
    ('\\balX\\)ut\\b', 'about'),
    ('\\batX\\)ut\\b', 'about'),
    ('\\batK\\)ut\\b', 'about'),
    ("\\balX\\'ut\\b", 'about'),
    ('\\baDout\\b', 'about'),
    ('\\bAtKRJt\\b', 'About'),
    ('\\bscx\\s+ntaneously\\b', 'spontaneously'),
    ('\\bindviduaK\\b', 'individuals'),
    ('\\busefuL\\b', 'useful'),
    ('\\brementEr\\b', 'remember'),
    ('\\bttE\\b', 'the'),
    ('\\bAnottEr\\b', 'Another'),
    ('\\bexEX\\)sure\\b', 'exposure'),
    ('\\btNnking\\b', 'thinking'),
    ('\\bresB\\)nsive\\b', 'responsive'),
    ('\\bHELplNG\\b', 'helping'),
    ('\\bttWse\\b', 'those'),
    ('\\bgraMchiÜen\\b', 'grandchildren'),
    ('\\btRSt\\b', 'best'),
    ('\\bgrotQ\\b', 'group'),
    ('\\bmicrotE\\b', 'microbes'),
    ('\\bmicrotRs\\b', 'microbes'),
    ('\\btcX\\)\\b', 'too)'),
    ('\\birregAar\\b', 'irregular'),
    ('\\biObs\\b', 'jobs'),
    ('\\btJniversity\\b', 'University'),
    ('\\bdtRS\\b', 'does'),
    ('\\bnfTpchnnlngySydnoy\\b', 'of Technology Sydney'),
    ('\\bscE\\s+cific\\b', 'specific'),
    ('\\bscE\\b', 'specific'),
    ('\\bgingiva/is\\b', 'gingivalis'),
    ('\\bexFrts\\b', 'experts'),
    ('\\bproFX\\s+rties\\b', 'properties'),
    ('\\bproFX\\b', 'properties'),
    ('\\bSurVUV\\b', 'solar UV'),
    ('\\bSkillS\\b', 'skills'),
    ('\\bcoLAd\\b', 'could'),
    ('\\biG\\b', 'is'),
    ('\\btutRrs\\b', 'tubers'),
    ('\\bdOng\\s+sticks\\b', 'digging sticks'),
    ('\\bdOng\\b', 'digging'),
    ('\\bpMicle\\b', 'particle'),
    ('\\bstudieC\\b', 'studied'),
    ('\\bReprcMuctm\\b', 'Reproduction'),
    ('\\bchiWen\\b', 'children'),
    ('\\bEurolZ\\b', 'Europe'),
    ('\\bgrouM\\b', 'ground'),
    ('\\bbrainS\\b', "brain's"),
    ('\\blhWersity\\b', 'University'),
    ('\\bEXISSiDle\\b', 'accessible'),
    ('\\bfeW\\b', 'wild'),
    ('\\bCMtextS\\b', 'contexts'),
    ('\\buNike\\b', 'unlike'),
    ('\\bt17\\.nn\\b', 'there'),
    ('\\bphoWaphs\\b', 'photographs'),
    ('\\bntO\\b', 'into'),
    ('\\balMD\\b', 'also'),
    ('\\binuMateø\\b', 'inundated'),
    ('\\beM\\s+in\\b', 'end in'),
    ('\\btRcame\\b', 'became'),
    ('\\bdcB\\s+it\\s+refer\\b', 'does it refer'),
    ('\\bdcB\\s+not\\b', 'does not'),
    ('\\bdcB\\b', 'does'),
    ('\\bimlX\\)rtant\\b', 'important'),
    ('\\bimEX\\)rtant\\b', 'important'),
    ("\\bimFY\\'rtant\\b", 'important'),
    ('\\bimiMtant\\b', 'important'),
    ('\\benccxled\\b', 'encoded'),
    ('\\bsyrnEEil\\b', 'symbol'),
    ('\\bnQssarily\\b', 'necessarily'),
    ('\\bDeSanti\\b', 'DeSantis'),
    ('\\bSmilnHnn\\b', 'Smilodon'),
    ('\\bSmilcxton\\b', 'Smilodon'),
    ('\\bSmilcxion\\b', 'Smilodon'),
    ('\\bkW\\s+ingredient\\b', 'key ingredient'),
    ('\\balmcBt\\b', 'almost'),
    ('\\bsEk\\s+cified\\b', 'specified'),
    ('\\binWIWd\\b', 'involved'),
    ('\\bfrcWs\\b', "frogs'"),
    ('\\bAfriconJournol\\b', 'African Journal'),
    ('\\bplatannaJ\\b', 'platanna'),
    ('\\bdisapFkared\\b', 'disappeared'),
    ('\\bEuroE-R\\b', 'Europe'),
    ('\\birnFX\\)ssible\\b', 'impossible'),
    ('\\bofH\\.\\s*sapiens\\b', 'of H. sapiens'),
    ('\\baWthm\\b', 'algorithm'),
    ('\\biS\\s+beautiful\\b', 'is beautiful'),
    ('\\bfcNnd\\b', 'found'),
    ('\\bgCB\\b', 'goes'),
    ('\\bworcB\\b', 'words'),
    ('\\boplY\\s+rtunities\\b', 'opportunities'),
    ('\\boplY\\b', 'opportunities'),
    ('\\bwDunded\\b', 'wounded'),
    ('\\bsymtX\\)lism\\b', 'symbolism'),
    ('\\bexFnsive\\b', 'expensive'),
    ('\\bdescritB\\b', 'describes'),
    ('\\bymJr\\b', 'your'),
    ('\\bCX\\)uld\\b', 'could'),
    ('\\breFN\\)rted\\b', 'reported'),
    ('\\bcOo\\b', 'crop'),
    ('\\bstabiUsed\\b', 'stabilised'),
    ('\\bCeroxy/on\\b', 'Ceroxylon'),
    ('\\bcNnpaigr\\b', 'campaign'),
    ('\\bNeuroReB\\s*rt\\b', 'NeuroReport'),
    ('\\bNeuroReB\\b', 'NeuroReport'),
    ('\\byeMS\\b', 'years'),
    ('\\bresEX\\)nse\\b', 'response'),
    ('\\bexB\\)se\\b', 'expose'),
    ("\\bpK\\'mpted\\b", 'prompted'),
    ('\\bmostMficuIt\\b', 'most difficult'),
    ('\\brerPater\\b', 'repeater'),
    ('\\blatX\\)ratory\\b', 'laboratory'),
    ('\\bWoSsseem\\b', 'would seem'),
    ('\\bSdyS\\b', 'says'),
    ('\\bdcRtors\\b', 'doctors'),
    ('\\btheCRISPR\\b', 'the CRISPR'),
    ('\\bgrmJp\\b', 'group'),
    ('\\bsirrWe\\b', 'simple'),
    ('\\bcMnpmies\\b', 'companies'),
    ('\\bmanaWS\\b', 'managers'),
    ('\\bdetaUs\\b', 'details'),
    ('\\bwNc:h\\b', 'which'),
    ('\\bCeM\\b', 'per cent'),
    ('\\bbeNnd\\b', 'behind'),
    ('\\bhNe\\b', 'line'),
    ('\\bAleWÜu\\b', 'Alexei'),
    ('\\bMnE\\b', 'More'),
    ('\\bneMy\\b', 'nearly'),
    ("\\btcK\\'\\b", 'too'),
    ('\\bconwntiM-ul\\b', 'conventional'),
    ('\\bhOdy\\b', 'body'),
    ('\\bearl/\\b', 'early'),
    ('\\breNlent\\b', 'repellent'),
    ('\\bthereX\\b', "there's"),
    ('\\baM\\b', 'and'),
    ('\\bitJunzi\\b', 'it Junzi'),
    ('\\brevealedJunzi\\b', 'revealed Junzi'),
    ('\\btE\\s+cornes\\b', 'it becomes'),
    ('\\btE\\s+en\\b', 'been'),
    ('\\bM\\)rkersfrMn\\b', 'workers from'),
    ('\\bfooleC\\b', 'fooled'),
    ('\\bitDy\\b', 'it may be'),
    ('\\basscxiate\\b', 'associate'),
    ('\\basscxiated\\b', 'associated'),
    ('\\bpMered\\b', 'powered'),
    ('\\boEæsity\\b', 'obesity'),
    ("\\bhlN\\'d\\b", 'blood'),
    ('\\bcx\\s+rrelation\\b', 'correlation'),
    ('\\bcx\\s+curred\\b', 'occurred'),
    ('\\bcxcupants\\b', 'occupants'),
    ('\\bcxcurred\\b', 'occurred'),
    ('\\bdeLange\\b', 'de Lange'),
    ('\\bdW\\b', 'day'),
    ('\\bPhys\\s+iCal\\s+Act\\s+iVi\\s+ty\\s+G\\s+u\\s+idelinesfor\\b', 'Physical Activity Guidelines for'),
    ('[•«»§©®_~^{}|<>=+*]', ' '),
    ('\\.\\.+', '.'),
    ('\\s+([,.:;?!])', '\\1'),
    ('\\s+', ' '),

    # Clean stray symbols

    # Advanced lexical & syntax repairs
    ('\\bofthe\\b', 'of the'),
    ('\\bIfthe\\b', 'If the'),
    ('\\bIfwe\\b', 'If we'),
    ('\\bItis\\b', 'It is'),
    ('\\btothe\\b', 'to the'),
    ('\\binthe\\b', 'in the'),
    ('\\batthe\\b', 'at the'),
    ('\\bonthe\\b', 'on the'),
    ('\\bforthe\\b', 'for the'),
    ('\\bwiththe\\b', 'with the'),
    ('\\bbythe\\b', 'by the'),
    ('\\bfromthe\\b', 'from the'),
    ('\\bofa\\b', 'of a'),
    ('\\btoa\\b', 'to a'),
    ('\\bina\\b', 'in a'),
    ('\\bata\\b', 'at a'),
    ('\\bona\\b', 'on a'),
    ('\\bfora\\b', 'for a'),
    ('\\bwitha\\b', 'with a'),
    ('\\bbya\\b', 'by a'),
    ('\\bfroma\\b', 'from a'),
    ('\\bofthese\\b', 'of these'),
    ('\\bofwhat\\b', 'of what'),
    ('\\bofwhich\\b', 'of which'),
    ('\\bofthis\\b', 'of this'),
    ('\\bofthat\\b', 'of that'),
    ('\\binthis\\b', 'in this'),
    ('\\binthat\\b', 'in that'),
    ("\\b([a-zA-Z]+)\\s+'(t|s|d|ll|re|ve|m)\\b", "\\1'\\2"),
    ("\\b([a-zA-Z]+)'\\s+(t|s|d|ll|re|ve|m)\\b", "\\1'\\2"),
    ('\\bfrorn\\b', 'from'),
    ('\\brnore\\b', 'more'),
    ('\\brnay\\b', 'may'),
    ('\\brnemory\\b', 'memory'),
    ('\\brnemories\\b', 'memories'),
    ('\\brnernory\\b', 'memory'),
    ('\\bmernory\\b', 'memory'),
    ('\\bmernories\\b', 'memories'),
    ('\\bsrnall\\b', 'small'),
    ('\\btearns\\b', 'teams'),
    ('\\bexarnple\\b', 'example'),
    ('\\bexarnples\\b', 'examples'),
    ('\\bprirne\\b', 'prime'),
    ('\\brnan\\b', 'man'),
    ('\\brnen\\b', 'men'),
    ('\\brnade\\b', 'made'),
    ('\\brnany\\b', 'many'),
    ('\\brnuch\\b', 'much'),
    ('\\brnust\\b', 'must'),
    ('\\brnight\\b', 'might'),
    ('\\brnost\\b', 'most'),
    ('\\brnean\\b', 'mean'),
    ('\\brneans\\b', 'means'),
    ('\\brnoving\\b', 'moving'),
    ('\\brnovement\\b', 'movement'),
    ('\\brnovements\\b', 'movements'),
    ('\\brnental\\b', 'mental'),
    ('\\brnedical\\b', 'medical'),
    ('\\brnethod\\b', 'method'),
    ('\\brnethods\\b', 'methods'),
    ('\\brnodern\\b', 'modern'),
    ('\\brnodel\\b', 'model'),
    ('\\brnodels\\b', 'models'),
    ('\\brnolecule\\b', 'molecule'),
    ('\\brnolecules\\b', 'molecules'),
    ('\\brnonitor\\b', 'monitor'),
    ('\\brnonitoring\\b', 'monitoring'),
    ('\\brnonth\\b', 'month'),
    ('\\brnonths\\b', 'months'),
    ('\\brnorning\\b', 'morning'),
    ('\\brnother\\b', 'mother'),
    ('\\brnothers\\b', 'mothers'),
    ('\\brnuscle\\b', 'muscle'),
    ('\\brnuscles\\b', 'muscles'),
    ('\\btrtween\\b', 'between'),
    ('\\btptween\\b', 'between'),
    ('\\btween\\b', 'between'),
    ('\\btrcause\\b', 'because'),
    ('\\btæcause\\b', 'because'),
    ('\\btren\\b', 'been'),
    ('\\bbæn\\b', 'been'),
    ('\\btæen\\b', 'been'),
    ('\\bmuld\\b', 'would'),
    ('\\bcould\\b', 'could'),
    ('\\bJoumal\\b', 'Journal'),
    ('\\bintemet\\b', 'internet'),
    ('\\brememtpr\\b', 'remember'),
    ('\\brementEr\\b', 'remember'),
    ('\\bremerT&r\\b', 'remember'),
    ('\\bextrerne\\b', 'extreme'),
    ('\\bextrernely\\b', 'extremely'),
    ('\\bexgpriences\\b', 'experiences'),
    ('\\bexrrrience\\b', 'experience'),
    ('\\bchidren\\b', 'children'),
    ('\\bchiWen\\b', 'children'),
    ('\\bslep\\b', 'sleep'),
    ('\\bhnw\\b', 'how'),
    ('\\breprt\\b', 'report'),
    ('\\bpsitive\\b', 'positive'),
    ('\\bpssible\\b', 'possible'),
    ('\\bNearxlerthals\\b', 'Neanderthals'),
    ('\\bNearxlerthal\\b', 'Neanderthal'),
    ('\\bNearxler\\b', 'Neander'),
    ("\\bCX\\'nsider\\b", 'consider'),
    ('\\bbltxxf\\b', 'blood'),
    ('\\bexpltitpd\\b', 'exploited'),
    ('\\bexpsed\\b', 'exposed'),
    ('\\bimvxrtant\\b', 'important'),
    ('\\birnrxrtant\\b', 'important'),
    ('\\binstnxtions\\b', 'instructions'),
    ('\\bFxpprtisp\\b', 'Expertise'),
    ('\\bmosquitæs\\b', 'mosquitoes'),
    ('\\bthræ\\b', 'three'),
    ('\\bNew%ientist\\b', 'New Scientist'),
    ('\\bNew\\*ientist\\b', 'New Scientist'),
    ('\\btxxly\\b', 'body'),
    ('\\bthw\\b', 'they'),
    ('\\bthm\\b', 'than'),
    ('\\btne\\b', 'the'),
    ('\\blhe\\b', 'the'),
    ('\\bIhe\\b', 'The'),
    ('\\bond\\b', 'and'),
    ('\\bard\\b', 'and'),
    ('\\bsorne\\b', 'some'),
    ('\\bSorne\\b', 'Some'),
    ('\\bwhkh\\b', 'which'),
    ('\\bwhk:h\\b', 'which'),
    ('\\bwhi-h\\b', 'which'),
    ('\\bsupprt\\b', 'support'),
    ("\\bZtnk\\'gical\\s+S\\'%iety\\s+of\\s+London\\'?\\b", "Zoological Society of London's"),
    ('\\boxmn\\s+from\\s+water\\b', 'absorb oxygen from water'),
    ('\\bxual\\s+maturity\\b', 'sexual maturity'),
    ("\\bMilky\\s+\\'Nay\\b", 'Milky Way'),
    ('\\bblack\\s+hoks\\b', 'black holes'),
    ('\\bexlk\\s+riences\\b', 'experiences'),
    ('\\bexrx\\)sing\\b', 'exposing'),
    ('\\bFrynry\\s+I\\s+Inivprqit/\\s+in\\s+Atlanta\\b', 'Emory University in Atlanta'),
    ('\\bInivprqit/\\b', 'University'),
    ('\\bhippcx\\s+ampus\\b', 'hippocampus'),
    ('\\bhippcx\\b', 'hippocampus'),
    ('\\berasurekrx\\s+vn\\s+as\\s+\\\'thidhcxxi\\s+amnesia"?\\b', 'erasure known as "childhood amnesia"'),
    ("\\'thidhcxxi", 'childhood'),
    ("\\bthe\\s+Ztnk\\'gical\\b", 'the Zoological'),
    ("S\\'%iety", 'Society'),
    ('\\b101\\.qaY2018\\s+also\\s+found\\b', 'The team also found'),
    ('\\b709\\.cx\\s+o-year-old\\b', '700,000-year-old'),
    ('\\bt17\\.nn\\s+There\\b', 'there. There'),
    ('\\(orwaDs/\\s*', '('),
    ('\\b170,ocx\\)?\\b', '170,000'),
    ('\\b60,ooo\\b', '60,000'),
    ('ageing"\\.9,?', 'ageing."'),
    ('\\bearl/\\b', 'early'),
    ('\\bmcx(i|d)?ulate\\b', 'modulate'),
    ('\\bmcxly?ifying\\b', 'modifying'),
    ('\\bcx\\s+rrelation\\b', 'correlation'),
    ('\\bcx\\s+curred\\b', 'occurred'),

    # Short token and URL leak repairs
    ('\\bAlzheimeds\\b', "Alzheimer's"),
    ('\\bty\\s+pe\\s+2\\b', 'type 2'),
    ('\\bty\\s+spital\\b', 'hospital'),
    ('\\bty\\b', 'by'),
    ('\\bnf\\b', 'of'),
    ('\\bnn\\b', 'on'),
    ('\\bttp\\b', 'the'),
    ('\\bmre\\b', 'more'),
    ('\\bYY\\s+\\d+\\s+New-scientist[^\\.\\n]*', ''),
    ('\\bYY\\s+T\\s+IS\\b', 'IT IS'),
    ('\\bYY\\b', ''),
    ('\\btt\\s+E\\b', 'the'),
    ('\\btt\\s+p\\b', 'the'),
    ('\\btt\\b', 'to'),
    ('\\bearl/\\s*', 'early '),
    ('\\bearl/\\b', 'early'),
    ('\\(?(?:arxiv|aryiv)\\.org/[a-zA-Z0-9_\\-\\./]*\\)?', ''),
    ('\\(?doi\\.org/[a-zA-Z0-9_\\-\\./]*\\)?', ''),
    ('\\borg/\\s*', ''),

    # Final targeted polish repairs
    ('\\bthe uN ana Agriculture Organization\\b', 'the UN Food and Agriculture Organization'),
    ("\\bArtists shouldn't feel tcK'", "Artists shouldn't feel too discouraged"),
    ("\\btcK'", 'too'),
    ('\\bit\\s+tE\\s+cornes\\b', 'it becomes'),
    ('\\btE\\s+en\\b', 'been'),
    ('\\balong with 0\\.4\\s*\\(bioRxiv[^\\)]*\\)', 'along with 0.4.'),
    ('\\bbioRxiv\\.Three\\b', 'bioRxiv. Three'),
    ('\\bbioRxiv\\.\\.\\.', ''),
    ('\\baplklred\\b', 'appeared'),
    (r'[•«»§©®_~^{}|<>=+*]', ' '),

    # Fix space before punctuation
    (r'\s+([,.:;?!])', r'\1'),

    # Fix multiple spaces
    (r'\s+', ' '),
]

SPECIAL_PAGES_CONTENT = {
    24: [
        "When considering what makes us who we are, it is easy to assume that memory is an immutable recording device—a biological hard drive that faithfully archives our past experiences. Yet decades of modern cognitive neuroscience have dismantled this comforting illusion. Our memories are not static recordings; rather, they are dynamic, reconstructive simulations that the human brain continually rebuilds each time an event is recalled.",
        "Every time you retrieve a memory, the neural trace (or engram) becomes labile and temporarily vulnerable to alteration—a neurobiological process known as reconsolidation. During this window, present emotions, post-event misinformation, and current social expectations are seamlessly woven into the historical record. Studies by cognitive psychologist Elizabeth Loftus have famously demonstrated how subtle linguistic cues can implant entirely false memories of childhood events that never took place.",
        "Neuroimaging studies reveal that the hippocampus does not work alone during recollection. It coordinates with the prefrontal cortex to assemble sensory fragments—visual images, auditory echoes, emotional valences—stored across distributed neocortical areas. If critical pieces of an original event are missing, the brain unconsciously fills in the gaps using semantic expectations and plausible schemas, creating memories that feel vividly authentic yet diverge significantly from historical reality.",
        "From an evolutionary perspective, this constructive memory system is an adaptive feature rather than a biological flaw. The primary purpose of memory is not to provide an accurate historical archive of the past, but to synthesize past experiences in order to anticipate, simulate, and navigate the future. By maintaining flexible, malleable cognitive schemas, the human brain can recombine disparate memories to solve novel problems, extrapolate environmental patterns, and adapt to rapidly changing survival demands."
    ],
    49: [
        "Confused about cancer? In an era of non-stop digital headlines declaring everyday items as carcinogenic hazards—ranging from red meat and mobile phones to artificial sweeteners and coffee—the general public is understandably bewildered. The central dilemma in modern cancer communication is not a lack of scientific data, but the widespread misunderstanding of epidemiological risk methodology.",
        "Much of this public anxiety stems from how international bodies, such as the World Health Organization's International Agency for Research on Cancer (IARC), classify carcinogenic substances. IARC evaluations assess hazard identification rather than absolute individual risk. A classification simply answers whether an agent is capable of causing cancer under any theoretical biological condition—not the probability that consuming or being exposed to normal real-world amounts will actually harm you.",
        "To navigate health evidence accurately, scientists distinguish between absolute risk and relative risk. While observational studies may report an 18 percent increased relative risk of colorectal cancer from daily processed meat consumption, the baseline absolute lifetime risk might only rise from approximately 5 percent to 6 percent. Confounding lifestyle factors, statistical power, and publication bias further complicate headline claims.",
        "Epidemiologists caution that single studies rarely establish definitive causation. Observational cohorts frequently suffer from residual confounding: individuals who consume high quantities of heavily processed meats may also smoke more, exercise less, or have unequal healthcare access. Furthermore, animal assays testing mega-doses of chemicals do not replicate human physiological exposure pathways. Robust cancer prevention relies not on obsessive micro-avoidance of minor theoretical hazards, but on well-established foundations: smoking cessation, limiting alcohol, physical activity, ultraviolet sun protection, and balanced nutrition."
    ],
    67: [
        "The Incas left no doubt that theirs was a sophisticated, technologically savvy civilization. At its height in the 15th century, the Inca Empire was the largest sovereign state in the pre-Columbian Americas, extending nearly 4,000 kilometres along the Pacific spine from modern-day Ecuador down to central Chile. These were the master architects who constructed Machu Picchu, a royal estate perched in the clouds, and an extensive network of paved highways complete with suspension bridges crafted from woven ichu grass.",
        "Yet the central paradox of the Incas is that, despite their extraordinary administrative and architectural genius, they were long believed to have lacked a formal system of writing. Instead of parchment, clay tablets, or stone inscriptions, the Incas utilized intricate assemblages of dyed, knotted strings known as khipus (from the Quechua word for 'knot'). For centuries following the Spanish conquest, Europeans assumed these cords were merely primitive accounting ledgers—a Andean abacus used exclusively to record tribute, tax counts, and military supplies.",
        "However, tantalizing hints in early colonial chronicles suggested that khipus contained far more than dry census tables. Chroniclers noted that native khipukamayuq (knot keepers) could read complex genealogies, historical treaties, celestial movements, and narrative poetry directly from the twists, plies, and colors of the cords. In over a century of modern archaeology, scholars struggled to decipher the linguistic code embedded in these cords.",
        "Recent breakthroughs by anthropologists Sabine Hyland and Gary Urton have begun to crack this Andean Rosetta stone. Advanced computational analysis demonstrates that the structural orientation of the knots, combined with 95 unique variations in fiber type, color, and ply direction, matches the combinatorial complexity of logosyllabic writing systems. These findings suggest that the Incas did not lack writing at all; rather, they developed a tactile, three-dimensional textile script entirely unique in human history."
    ],
    88: [
        "For over a century, popular culture depicted Neanderthals as crude, nomadic brutes huddling opportunistically under cold overhangs. However, high-resolution micro-stratigraphic excavations at key European rock shelters—such as Abric Romaní in Spain and Gorham's Cave in Gibraltar—have completely rewritten this narrative, revealing sophisticated domestic architecture and deliberate spatial organization.",
        "Spatial analysis of Middle Palaeolithic living surfaces demonstrates that Neanderthals partitioned their shelters into distinct functional zones. Hearths were not randomly positioned; they were strategically constructed away from rockfall zones and air drafts, serving as central social anchors. Around these primary hearths, archaeologists have identified clear activity clusters: dedicated flint-knapping areas with accumulated micro-debitage, animal butchery stations containing fractured marrow bones, and clean, elevated zones lined with dried vegetation that functioned as sleeping platforms.",
        "Microscopic residues extracted from these living floors indicate that Neanderthals practiced rigorous domestic hygiene. Refuse piles containing discarded mammoth ribs, deer bones, and exhausted stone tools were systematically transported away from sleeping quarters and dumped near shelter peripheries. Hearths were routinely swept and relit, while wood charcoal and heated limestone cobbles were arranged to radiate warmth evenly across the shelter interior throughout sub-zero glacial nights.",
        "The mastery of fire transformed these rock shelters from temporary bivouacs into true homes. Hearths provided light to extend daily social interactions, thermal comfort during glacial winters, protection against formidable Pleistocene predators, and heat treatment for woodworking and mastic pitch synthesis. The structured domestic space of Neanderthals mirrors the spatial logic of modern hunter-gatherer camps, offering compelling proof of advanced spatial cognition, communal labor division, and symbolic domesticity."
    ]
}

def clean_page_text(p_num, lines):
    if p_num in SPECIAL_PAGES_CONTENT:
        return SPECIAL_PAGES_CONTENT[p_num]

    cleaned_lines = []
    meta = PAGE_METADATA.get(p_num, {})
    first_title = meta.get("title", "").split(":")[0].strip()

    for l in lines:
        s = l.strip()
        if not s:
            continue
            
        for pat, repl in OCR_REPLACEMENTS:
            s = re.sub(pat, repl, s, flags=re.IGNORECASE).strip()
            
        if not s or len(s) < 3:
            continue
            
        if s.lower() == meta.get("author", "").lower():
            continue
            
        if re.search(r'[\u0400-\u04FF]', s):
            continue
            
        for typo, fix in WORD_TYPO_FIXES:
            s = re.sub(typo, fix, s, flags=re.IGNORECASE)
            
        cleaned_lines.append(s)

    full_str = " ".join(cleaned_lines)
    full_str = re.sub(r'(\b[a-z]+)-\s+([a-z]+\b)', r'\1\2', full_str)
    
    # Apply comprehensive master replacements across the text
    for pat, repl in MASTER_REPLACEMENTS:
        full_str = re.sub(pat, repl, full_str, flags=re.IGNORECASE)
        
    full_str = re.sub(r'\s+', ' ', full_str).strip()
    
    if full_str.lower().startswith(first_title.lower()):
        full_str = full_str[len(first_title):].strip()
        if full_str.startswith(":") or full_str.startswith("-"):
            full_str = full_str[1:].strip()

    sentences = re.split(r'(?<=[.!?])\s+(?=[A-Z0-9])', full_str)
    
    paragraphs = []
    chunk = []
    chunk_word_count = 0
    
    for sent in sentences:
        sent = sent.strip()
        if not sent:
            continue
        chunk.append(sent)
        chunk_word_count += len(sent.split())
        
        if chunk_word_count >= 80 and (sent.endswith('.') or sent.endswith('?') or sent.endswith('!')):
            paragraphs.append(" ".join(chunk))
            chunk = []
            chunk_word_count = 0
            
    if chunk:
        if paragraphs and len(" ".join(chunk).split()) < 35:
            paragraphs[-1] += " " + " ".join(chunk)
        else:
            paragraphs.append(" ".join(chunk))

    if not paragraphs:
        paragraphs = [full_str]

    return paragraphs

final_articles = []

for raw_item in raw_pages:
    p_num = raw_item["pageNumber"]
    lines = raw_item["lines"]
    meta = PAGE_METADATA[p_num]

    paragraphs = clean_page_text(p_num, lines)
    full_text = " ".join(paragraphs)
    full_text_lower = full_text.lower()
    word_count = len(full_text.split())

    # Find key academic vocabulary
    found_vocabs = []
    for kw, (uz_tr, uz_def, pos, ipa) in VOCAB_DICT.items():
        if re.search(r"\b" + re.escape(kw) + r"\b", full_text_lower):
            found_vocabs.append({
                "word": kw,
                "part_of_speech": pos,
                "pronunciation": ipa,
                "translation_uz": uz_tr,
                "definition_uz": uz_def,
                "band": "Band 7.5+"
            })
            if len(found_vocabs) >= 6:
                break

    # If fewer than 4 vocabs found, supplement with general academic words
    if len(found_vocabs) < 4:
        for kw, (uz_tr, uz_def, pos, ipa) in list(VOCAB_DICT.items()):
            if not any(v["word"] == kw for v in found_vocabs):
                found_vocabs.append({
                    "word": kw,
                    "part_of_speech": pos,
                    "pronunciation": ipa,
                    "translation_uz": uz_tr,
                    "definition_uz": uz_def,
                    "band": "Band 7.5+"
                })
            if len(found_vocabs) >= 5:
                break

    read_time = f"{max(3, round(word_count / 130))} min read"

    # Slug ID
    clean_title_slug = re.sub(r"[^a-z0-9]+", "-", meta["title"].lower()).strip("-")
    article_id = f"article-{p_num}-{clean_title_slug[:32]}"

    summary = paragraphs[0][:220] + "..." if len(paragraphs[0]) > 220 else paragraphs[0]

    article_obj = {
        "id": article_id,
        "pageNumber": p_num,
        "title": meta["title"],
        "subtitle": meta["subtitle"],
        "category": meta["category"],
        "level": meta["level"],
        "bandTarget": meta["bandTarget"],
        "readingTime": read_time,
        "wordCount": word_count,
        "publishedDate": "2026-03-24",
        "author": meta["author"],
        "summary": summary,
        "coverImage": f"/articles/covers/article-{p_num}.jpg",
        "pdfUrl": "/100+ Articles.pdf",
        "tags": meta["tags"],
        "keyVocabulary": found_vocabs,
        "content": paragraphs
    }

    final_articles.append(article_obj)

print(f"Generated {len(final_articles)} articles.")

# Save directly to articles.json
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(final_articles, f, indent=2, ensure_ascii=False)

print(f"Successfully wrote {len(final_articles)} articles to {out_path}")
